/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * The job creation request.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ExperimentalCreateJobRequest extends com.google.api.client.json.GenericJson {

  /**
   * Specifies whether or not to run the alignment pipeline. At least one of align or call_variants
   * must be provided.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean align;

  /**
   * Specifies whether or not to run the variant calling pipeline. If specified, alignment will be
   * performed first and the aligned BAMs will passed as input to the variant caller. At least one
   * of align or call_variants must be provided.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean callVariants;

  /**
   * Specifies where to copy the results of certain pipelines. This shoud be in the form of
   * "gs://bucket/path".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcsOutputPath;

  /**
   * Required. The Google Cloud Project ID with which to associate the request.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long projectId;

  /**
   * Required. A list of Google Cloud Storage URIs of data files to operate upon.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> sourceUris;

  /**
   * Specifies whether or not to run the alignment pipeline. At least one of align or call_variants
   * must be provided.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAlign() {
    return align;
  }

  /**
   * Specifies whether or not to run the alignment pipeline. At least one of align or call_variants
   * must be provided.
   * @param align align or {@code null} for none
   */
  public ExperimentalCreateJobRequest setAlign(java.lang.Boolean align) {
    this.align = align;
    return this;
  }

  /**
   * Specifies whether or not to run the variant calling pipeline. If specified, alignment will be
   * performed first and the aligned BAMs will passed as input to the variant caller. At least one
   * of align or call_variants must be provided.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCallVariants() {
    return callVariants;
  }

  /**
   * Specifies whether or not to run the variant calling pipeline. If specified, alignment will be
   * performed first and the aligned BAMs will passed as input to the variant caller. At least one
   * of align or call_variants must be provided.
   * @param callVariants callVariants or {@code null} for none
   */
  public ExperimentalCreateJobRequest setCallVariants(java.lang.Boolean callVariants) {
    this.callVariants = callVariants;
    return this;
  }

  /**
   * Specifies where to copy the results of certain pipelines. This shoud be in the form of
   * "gs://bucket/path".
   * @return value or {@code null} for none
   */
  public java.lang.String getGcsOutputPath() {
    return gcsOutputPath;
  }

  /**
   * Specifies where to copy the results of certain pipelines. This shoud be in the form of
   * "gs://bucket/path".
   * @param gcsOutputPath gcsOutputPath or {@code null} for none
   */
  public ExperimentalCreateJobRequest setGcsOutputPath(java.lang.String gcsOutputPath) {
    this.gcsOutputPath = gcsOutputPath;
    return this;
  }

  /**
   * Required. The Google Cloud Project ID with which to associate the request.
   * @return value or {@code null} for none
   */
  public java.lang.Long getProjectId() {
    return projectId;
  }

  /**
   * Required. The Google Cloud Project ID with which to associate the request.
   * @param projectId projectId or {@code null} for none
   */
  public ExperimentalCreateJobRequest setProjectId(java.lang.Long projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Required. A list of Google Cloud Storage URIs of data files to operate upon.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getSourceUris() {
    return sourceUris;
  }

  /**
   * Required. A list of Google Cloud Storage URIs of data files to operate upon.
   * @param sourceUris sourceUris or {@code null} for none
   */
  public ExperimentalCreateJobRequest setSourceUris(java.util.List<java.lang.String> sourceUris) {
    this.sourceUris = sourceUris;
    return this;
  }

  @Override
  public ExperimentalCreateJobRequest set(String fieldName, Object value) {
    return (ExperimentalCreateJobRequest) super.set(fieldName, value);
  }

  @Override
  public ExperimentalCreateJobRequest clone() {
    return (ExperimentalCreateJobRequest) super.clone();
  }

}
