/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * The readset export response.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ExportReadsetsResponse extends com.google.api.client.json.GenericJson {

  /**
   * An export ID that can be used to get status information.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger exportId;

  /**
   * An export ID that can be used to get status information.
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getExportId() {
    return exportId;
  }

  /**
   * An export ID that can be used to get status information.
   * @param exportId exportId or {@code null} for none
   */
  public ExportReadsetsResponse setExportId(java.math.BigInteger exportId) {
    this.exportId = exportId;
    return this;
  }

  @Override
  public ExportReadsetsResponse set(String fieldName, Object value) {
    return (ExportReadsetsResponse) super.set(fieldName, value);
  }

  @Override
  public ExportReadsetsResponse clone() {
    return (ExportReadsetsResponse) super.clone();
  }

}
